apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.rootPassword }}
  MYSQL_PASSWORD: {{ .Values.secret.password }}
  MYSQL_DATABASE: {{ .Values.mysql.database }}
